/* eslint-disable @next/next/no-html-link-for-pages */

import { Container, Wrapper } from "../../ui";
import { useTranslations } from "next-intl";
import { Logo } from "../../ui/Logo";
import { NavMenu } from "./NavMenu";
import { useRouter } from "next/router";
import { homeUrl } from "@/src/functions";
import Head from "next/head";

export const Header = () => {
  const t = useTranslations("header");
  const router = useRouter();

  return (
    <>
      <Head>
        <title>ArtisanNow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper className="relative">
        <div className="w-full bg-white fixed top-0 z-20 border-b">
          <header className="w-full">
            <div className="flex w-full h-full justify-content items-center relative px-5 md:px-20 py-2 md:py-4">
              <div className="Logo">
                <Logo />
              </div>
              <div></div>
              <nav className="ml-auto flex items-center lg:space-x-6 space-x-2">
                <NavMenu />
              </nav>
            </div>
          </header>
        </div>

      </Wrapper>
      {router.asPath !== homeUrl && (
        <Wrapper className="relative mt-[69px]">
        </Wrapper>
      )}
    </>
  );
};
